"""Add is_out_of_town to projects

Revision ID: eb9d0afdbe82
Revises: 
Create Date: 2026-01-23 16:51:06.623075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9d0afdbe82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crew_types_id'), 'crew_types', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('project_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('budgeted_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_mechanical', sa.Boolean(), nullable=True),
    sa.Column('is_electrical', sa.Boolean(), nullable=True),
    sa.Column('is_vesda', sa.Boolean(), nullable=True),
    sa.Column('is_aws', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('project_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('schedule_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='schedule_date_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_schedules_end_date'), 'project_schedules', ['end_date'], unique=False)
    op.create_index(op.f('ix_project_schedules_id'), 'project_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_project_schedules_project_id'), 'project_schedules', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_schedules_start_date'), 'project_schedules', ['start_date'], unique=False)
    op.create_table('schedule_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('estimated_man_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('crew_size', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('crew_type_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='phase_date_check'),
    sa.ForeignKeyConstraint(['crew_type_id'], ['crew_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['project_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_phases_crew_type_id'), 'schedule_phases', ['crew_type_id'], unique=False)
    op.create_index(op.f('ix_schedule_phases_end_date'), 'schedule_phases', ['end_date'], unique=False)
    op.create_index(op.f('ix_schedule_phases_id'), 'schedule_phases', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_phases_schedule_id'), 'schedule_phases', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_phases_start_date'), 'schedule_phases', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_phases_start_date'), table_name='schedule_phases')
    op.drop_index(op.f('ix_schedule_phases_schedule_id'), table_name='schedule_phases')
    op.drop_index(op.f('ix_schedule_phases_id'), table_name='schedule_phases')
    op.drop_index(op.f('ix_schedule_phases_end_date'), table_name='schedule_phases')
    op.drop_index(op.f('ix_schedule_phases_crew_type_id'), table_name='schedule_phases')
    op.drop_table('schedule_phases')
    op.drop_index(op.f('ix_project_schedules_start_date'), table_name='project_schedules')
    op.drop_index(op.f('ix_project_schedules_project_id'), table_name='project_schedules')
    op.drop_index(op.f('ix_project_schedules_id'), table_name='project_schedules')
    op.drop_index(op.f('ix_project_schedules_end_date'), table_name='project_schedules')
    op.drop_table('project_schedules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_crew_types_id'), table_name='crew_types')
    op.drop_table('crew_types')
    # ### end Alembic commands ###
