"""Add sub_headcount to projects

Revision ID: fd781e8b9d9e
Revises: a1b2c3d4e5f6
Create Date: 2026-01-30 18:37:01.578599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd781e8b9d9e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_subcontractors', sa.Column('headcount', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('is_out_of_town', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('sub_headcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sub_headcount')
    op.drop_column('projects', 'is_out_of_town')
    op.drop_column('project_subcontractors', 'headcount')
    # ### end Alembic commands ###
