# Generated by Django 5.2 on 2025-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
