import React from 'react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
}

export default function DisclaimerModal({ isOpen, onAccept }: DisclaimerModalProps) {
  if (!isOpen) return null;

  const isMobile = window.innerWidth < 768;

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        background: 'rgba(0,0,0,0.6)',
        backdropFilter: 'blur(8px)',
        zIndex: 3000,
        padding: isMobile ? '10px' : '20px',
        boxSizing: 'border-box',
        overflow: 'auto',
        WebkitOverflowScrolling: 'touch',
      } as React.CSSProperties}
    >
      <div
        style={{
          background: '#fff',
          borderRadius: isMobile ? 8 : 12,
          padding: isMobile ? '20px' : '32px',
          width: '100%',
          maxWidth: isMobile ? '100%' : '600px',
          margin: '0 auto',
          marginTop: isMobile ? '20px' : '60px',
          minHeight: 'fit-content',
          boxShadow: '0 8px 48px rgba(0,0,0,0.2)',
          position: 'relative',
        }}
      >
        {/* Warning Icon */}
        <div style={{ textAlign: 'center', marginBottom: 20 }}>
          <div
            style={{
              display: 'inline-block',
              width: 60,
              height: 60,
              borderRadius: '50%',
              background: '#fff3cd',
              border: '3px solid #ff9800',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 32,
              fontWeight: 'bold',
              color: '#ff9800',
            }}
          >
            ⚠
          </div>
        </div>

        {/* Title */}
        <h2
          style={{
            marginTop: 0,
            marginBottom: 20,
            color: '#1a2233',
            fontSize: isMobile ? '1.3rem' : '1.6rem',
            textAlign: 'center',
            fontWeight: 700,
          }}
        >
          Important Disclaimer
        </h2>

        {/* Disclaimer Content */}
        <div
          style={{
            color: '#444',
            fontSize: isMobile ? '0.9rem' : '1rem',
            lineHeight: 1.6,
            marginBottom: 24,
          }}
        >
          <div style={{ marginBottom: 16 }}>
            <strong style={{ color: '#d32f2f', fontSize: '1.05rem' }}>
              ⚠ PROFESSIONAL REVIEW REQUIRED
            </strong>
            <p style={{ margin: '8px 0' }}>
              All specifications generated by this tool must be reviewed and approved by a
              licensed fire protection engineer before fabrication or installation. This tool is
              for preliminary planning purposes only.
            </p>
          </div>

          <div style={{ marginBottom: 16 }}>
            <strong style={{ color: '#d32f2f', fontSize: '1.05rem' }}>
              ⚠ VERIFICATION OF SPECIFICATIONS
            </strong>
            <p style={{ margin: '8px 0' }}>
              Users are responsible for verifying all product specifications, sizes, quantities,
              and compatibility with applicable codes (NFPA, local AHJ) before ordering or
              installing materials.
            </p>
          </div>

          <div style={{ marginBottom: 16 }}>
            <strong style={{ color: '#d32f2f', fontSize: '1.05rem' }}>
              ⚠ NO WARRANTY / LIABILITY
            </strong>
            <p style={{ margin: '8px 0' }}>
              This application is provided "as-is" without warranties of any kind. The developer
              assumes no liability for errors, omissions, or consequences resulting from the use of
              this tool. Always consult manufacturer documentation and applicable fire protection
              standards.
            </p>
          </div>

          <div style={{ marginBottom: 0 }}>
            <strong style={{ color: '#d32f2f', fontSize: '1.05rem' }}>
              ⚠ PRODUCT INFORMATION ACCURACY
            </strong>
            <p style={{ margin: '8px 0' }}>
              Product information is for reference only. Specifications, availability, and
              compatibility may change. Always verify current product data with manufacturers
              before ordering.
            </p>
          </div>
        </div>

        {/* Accept Button */}
        <button
          onClick={onAccept}
          style={{
            width: '100%',
            background: '#1976d2',
            color: '#fff',
            border: 'none',
            borderRadius: 8,
            padding: isMobile ? '14px' : '16px',
            fontSize: isMobile ? '1rem' : '1.1rem',
            fontWeight: 700,
            cursor: 'pointer',
            boxShadow: '0 2px 8px rgba(25, 118, 210, 0.3)',
            transition: 'all 0.2s ease',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#1565c0';
            e.currentTarget.style.transform = 'translateY(-1px)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#1976d2';
            e.currentTarget.style.transform = 'translateY(0)';
          }}
        >
          I Understand and Accept
        </button>

        {/* Legal Note */}
        <p
          style={{
            marginTop: 16,
            marginBottom: 0,
            fontSize: '0.75rem',
            color: '#888',
            textAlign: 'center',
            fontStyle: 'italic',
          }}
        >
          By clicking "I Understand and Accept", you acknowledge that you have read and understood
          these disclaimers and agree to use this tool accordingly.
        </p>
      </div>
    </div>
  );
}
